#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#

language: c

compiler:
  - gcc
  - clang

# Only with gcc get the mingw-w64 cross compilers
before_install:
  - if [ $CC = 'gcc' ]; then sudo apt-get update -qq; sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686; fi


before_script:
    - sudo apt-get install -y valgrind

# Build and run tests. Only with gcc cross compile
script:
  - autoreconf -f -i -v
  - ./configure
  - make -j2
  - make check TRAVIS=1
  - make fuzz VG=1
  - if [ $CC = 'gcc' ]; then make distclean; make -f mk_mingw.mak CC=i686-w64-mingw32-gcc; fi
