name: build ctags with pegof and run units target on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    env:
       DEBIAN_FRONTEND: noninteractive

    steps:
      - run: sudo apt -y update
      - run: sudo apt -y install cmake g++ pkg-config automake libseccomp-dev libjansson-dev libyaml-dev libxml2-dev libpcre2-dev bash gdb python3-docutils
      # cmake and g++ are used to build pegof

      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: dolik-rce/pegof
          submodules: recursive
          fetch-tags: true
          path: pegof

      - run: cmake -S pegof -B pegof/build.d
      - run: cmake --build     pegof/build.d

      - run: pegof/build.d/pegof --version

      - run: ./autogen.sh
      - run: ./configure --enable-debugging --enable-iconv --with-pegof=$PWD/pegof/build.d/pegof

      - run: make -j2

      - run: ./ctags --list-features | grep pegof

      - run: |
          echo "Targets: $(./ctags --list-languages=_packcc |  while read LANG REST; do echo "$LANG"; done | tr '\n' ',')"
      - run: make units LANGUAGES="$(./ctags --list-languages=_packcc |  while read LANG REST; do echo "$LANG"; done | tr '\n' ',')"
      - run: make dist
        # See EXTRA_DIST in Makefile.am.
        # Currently we add .pego files.
