name: cross compile for Android on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        build-machine-os: [macos-15, macos-14, macos-13]

    runs-on: ${{ matrix.build-machine-os }}

    steps:
      - uses: actions/checkout@v4

      - run: brew install make automake autoconf file

      - run: ./autogen.sh

      - name: Run ./configure ...
        run: |
          TOOLCHAIN_BASE_DIR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64
          TOOLCHAIN_BIN_DIR=$TOOLCHAIN_BASE_DIR/bin
          SYSROOT=$TOOLCHAIN_BASE_DIR/sysroot

          export CC=$TOOLCHAIN_BIN_DIR/armv7a-linux-androideabi24-clang
          export AR=$TOOLCHAIN_BIN_DIR/llvm-ar
          export RANLIB=$TOOLCHAIN_BIN_DIR/llvm-ranlib

          export CFLAGS="--sysroot $SYSROOT -Qunused-arguments -Os -fpic"
          export CPPFLAGS="--sysroot $SYSROOT -Qunused-arguments"
          export LDFLAGS="--sysroot $SYSROOT"

          ./configure \
              --host=armv7a-linux-androideabi \
              --disable-iconv \
              --disable-xml \
              --disable-json \
              --disable-yaml \
              --disable-pcre2

      - run: make V=1

      - run: file ctags | grep 'ELF 32-bit LSB pie executable, ARM, EABI5'
