name: run units target on MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [macos-11, macos-12]
        compiler: [gcc, clang]

    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler }}
      BUILDDIR: ${{ matrix.os }}-${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v4

    # temporarily disabled, because it always fails these days.
    #- name: update package information
    #  run: brew update

    - name: install tools and libraries
      run: |
        # See https://github.com/actions/runner-images/issues/6817.
        brew install --overwrite python@3.10 python@3.11
        brew install automake pkg-config bash libxml2 jansson libyaml gdb docutils pcre2
    - name: autogen.sh
      run: ./autogen.sh
    - name: report the version of cc
      run: ${{ matrix.compiler }} --version
    - name: report the version of make
      run: make --version
    - name: configure
      run: |
        mkdir -p ${{ matrix.os }}-"$CC"
        (
          cd $BUILDDIR
          ../configure --enable-debugging --enable-iconv
        )
    - name: make
      run: make -C $BUILDDIR -j2
    - name: report features
      run: |
        (
          cd $BUILDDIR
          ./ctags --list-features
        )
    - name: make check
      run: make -C $BUILDDIR check
    - name: make roundtrip
      run: make -C $BUILDDIR roundtrip
