name: run units target on OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        openbsd-version: ['7.5', '7.4', '7.3', '7.2']

    steps:
      - uses: actions/checkout@v4

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: openbsd
          version: ${{ matrix.openbsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            export AUTOCONF_VERSION=2.69
            export AUTOMAKE_VERSION=1.16

            export  CFLAGS='-I/usr/local/include'
            export LDFLAGS='-L/usr/local/lib'

            run sudo pkg_add automake%1.16 gmake pkgconf jansson libyaml libxml libiconv

            run cc --version

            run ./autogen.sh
            run ./configure --prefix=/usr
            run gmake
            run sudo gmake install

            run readelf -h /usr/bin/ctags
            run readelf -d /usr/bin/ctags

            run ctags --version

            # bugs to fix
            #run make check CI=gha+vagrant+openbsd
            run gmake roundtrip CI=gha+vagrant+openbsd
