name: run units target on MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MSYS, MINGW32, MINGW64, CLANG32, CLANG64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - if: ${{ matrix.msystem == 'MSYS' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: automake autoconf make dos2unix gcc pkgconf python3 jansson libxml2 libyaml pcre2

    - if: ${{ matrix.msystem != 'MSYS' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: automake autoconf make dos2unix
        pacboy: toolchain:p python3-sphinx:p jansson:p libxml2:p libyaml:p pcre2:p

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v4

    - run: ./autogen.sh
    - run: ./configure --prefix=/usr
    - run: make V=1
    - run: make install
    - run: file /usr/bin/ctags
    - run: ctags --version

    - run: make check V=1

    # FAILED: "./readtags.exe" -t "/d/a/ctags2/ctags2/Units/parser-asciidoc.r/utf8-asciidoc.d/expected.tags" - "@–Ä‚ÄìêÄÄ"
    # The raw tag name was "@–Ä‚ÄìêÄÄ"
    - if: ${{ matrix.msystem == 'MSYS' }}
      run: make roundtrip

    - run: make tmain
    - run: make units
