name: run units target on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:

    strategy:
      matrix:
        os: [macos-15, macos-14, macos-26]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    # temporarily disabled, because it always fails these days.
    #- run: brew update

    # NOTE: DO NOT try to install libiconv and libxml2 package via brew, because macOS already provides them.
    # NOTE: DO NOT try to install python3 package via brew, it has already been included in macos-xx runner images
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md

    - if: matrix.os == 'macos-26'
      run: brew install --overwrite python@3.12

    - run: brew install automake jansson libyaml pcre2

    - run: pip3 install docutils --break-system-packages

    - run: cc --version
    - run: make --version

    - run: ./autogen.sh
    - run: ./configure --enable-debugging --enable-iconv
    - run: make -j2

    - run: ./ctags --version
    - run: ./ctags --list-features

    - run: make check
    - run: make roundtrip
    - run: make tmain
    - run: make units
